### PR TITLE
add task to install bundler

### PR DESCRIPTION
**Pull request by masarakki**
in many case, a lot of ruby codes depend on existence of `bundle` command as yet,
off cause I can't replace all gems to avoid `bundle` command,
so I want easy way to install `bundler`.

### CODE REVIEW

**Comment by StefSchenkelaars** [comment]
Please merge :+1:

**Comment by RyanMacG** [comment]
Trying to hack this in is a nightmare that I just lost a lot of time to, it really needs merged in.

shipitralph

**Comment by mpapis** [comment]
this is separate general purpose task, how about something like:
```bash
cap gem -s install=bundler
```
but this should not be part of rvm in any way

**Comment by itay-grudev** [comment]
This makes no sense. This gems installs `rvm` then `ruby` and required gems by the project, but not `bundler`. It's ridiculous. You are essentially missing a required step in the middle of the dependency chain. I vote to reopen this issue and install `bundler` when installing ruby.

**Comment by oma** [comment]
FYI: capistrano/bundler solves this. 
Adding this note as google took me here in my search and it wasa dead end.

**Comment by itay-grudev** [comment]
It's been a while, but the last time I checked it doesn't because of the difference in behaviour between `rvm/capistrano` and `rvm1-capistrano3`.

**Comment by oma** [comment]
I use `rvm1-capsitrano3`, not `rvm/capistrano`. Just sharing that it solved it for me, I tried this issue's hack first.

**Pull request closed without merging**
